{% set data = load_setup_py_data() %}

package:
  name: "pymt_landlab"
  version: {{ data.get('version') }}

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy 1.11.*
    - model_metadata
    - landlab 
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - landlab 

test:
  requires:
    - bmi-tester
    - model_metadata
  imports:
    - pymt_landlab
  commands:
    - config_file=$(mmd-stage OverlandFlow . > MANIFEST && mmd-query OverlandFlow --var=run.config_file.path)
    - bmi-test pymt_landlab.bmi:OverlandFlow --config-file=$config_file --manifest=MANIFEST -v
    - config_file=$(mmd-stage Flexure . > MANIFEST && mmd-query Flexure --var=run.config_file.path)
    - bmi-test pymt_landlab.bmi:Flexure --config-file=$config_file --manifest=MANIFEST -v
    - config_file=$(mmd-stage LinearDiffuser . > MANIFEST && mmd-query LinearDiffuser --var=run.config_file.path)
    - bmi-test pymt_landlab.bmi:LinearDiffuser --config-file=$config_file --manifest=MANIFEST -v
    - config_file=$(mmd-stage ExponentialWeatherer . > MANIFEST && mmd-query ExponentialWeatherer --var=run.config_file.path)
    - bmi-test pymt_landlab.bmi:ExponentialWeatherer --config-file=$config_file --manifest=MANIFEST -v
    - config_file=$(mmd-stage TransportLengthHillslopeDiffuser . > MANIFEST && mmd-query TransportLengthHillslopeDiffuser --var=run.config_file.path)
    - bmi-test pymt_landlab.bmi:TransportLengthHillslopeDiffuser --config-file=$config_file --manifest=MANIFEST -v
    - config_file=$(mmd-stage Vegetation . > MANIFEST && mmd-query Vegetation --var=run.config_file.path)
    - bmi-test pymt_landlab.bmi:Vegetation --config-file=$config_file --manifest=MANIFEST -v
    - config_file=$(mmd-stage SoilMoisture . > MANIFEST && mmd-query SoilMoisture --var=run.config_file.path)
    - bmi-test pymt_landlab.bmi:SoilMoisture --config-file=$config_file --manifest=MANIFEST -v

about:
  summary: Python package that wraps the landlab BMI.
  home: https://github.com/mcflugen/pymt_landlab
  license: MIT license
  license_file: LICENSE
  dev_url: https://github.com/mcflugen/pymt_landlab
