build:
  define_macros: []
  extra_compile_args: []
  include_dirs: []
  libraries: []
  library_dirs: []
  undef_macros: []
info:
  github_username: mcflugen
  plugin_author: Eric Hutton
  plugin_license: MIT
  summary: PyMT plugins for landlab components
library:
  entry_point:
  - OverlandFlow=landlab.bmi.components:OverlandFlow
  - Flexure=landlab.bmi.components:Flexure
  - LinearDiffuser=landlab.bmi.components:LinearDiffuser
  - ExponentialWeatherer=landlab.bmi.components:ExponentialWeatherer
  - TransportLengthHillslopeDiffuser=landlab.bmi.components:TransportLengthHillslopeDiffuser
  - Vegetation=landlab.bmi.components:Vegetation
  - SoilMoisture=landlab.bmi.components:SoilMoisture
  - DepthDependentDiffuser=landlab.bmi.components:DepthDependentDiffuser
  language: python
  register: ''
plugin:
  name: landlab
  requirements:
  - landlab
